## Numpy
numpyは数値計算ライブラリです。機械学習の場面では必須のライブラリであるため、その扱い方の一例を紹介します

公式ドキュメントURL
https://www.numpy.org/devdocs/reference/

In [3]:
"""読み込み
"""
import numpy as np

## 行列の基本
Numpyの行列は、N-dimentional array（N次元行列）の略称で**ndarray**と呼ばれています

In [4]:
"""一次元行列
"""
x=np.array([1,2])
print(x)
print(type(x))

[1 2]
<class 'numpy.ndarray'>


In [5]:
"""二次元行列
"""
x=np.array([[1,2],[3,4]])
print(x)
print(type(x))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [6]:
"""二次元行列
"""
x=np.array([[1,2],[3,4],[5,6]])
print(x)
print(type(x))

[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>


# 様々な行列の生成方法

機械学習の場面などでは、初期値として、行列を自動で生成する場面が多々あります

In [7]:
"""1からの連番
"""
x = np.arange(25)
print(x)
print(type(x))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
<class 'numpy.ndarray'>


In [8]:
"""1からの連番＆行数列数の指定
"""
x = np.arange(25).reshape(5, 5)
print(x)
print(type(x))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
<class 'numpy.ndarray'>


In [9]:
"""0行列作成
"""
x=np.zeros((10,10))
print(x)
print(type(x))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
<class 'numpy.ndarray'>


In [12]:
"""0行列作成＆行数列数の指定
"""
x = np.arange(25).reshape(5, 5)
x=np.zeros_like(x)
print(x)
print(type(x))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
<class 'numpy.ndarray'>


In [13]:
"""1行列作成
"""
x=np.ones((5,5))
print(x)
print(type(x))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
<class 'numpy.ndarray'>


In [14]:
"""1行列作成＆行数列数の指定
"""
x = np.arange(25).reshape(5, 5)
x=np.ones_like(x)
print(x)
print(type(x))

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
<class 'numpy.ndarray'>


In [15]:
"""一様乱数生成
0以上1以下
"""
x=np.random.rand(10,2)
print(x)
print(type(x))

[[0.92405556 0.28220386]
 [0.33104059 0.46277524]
 [0.49022007 0.90832391]
 [0.93475995 0.35847024]
 [0.13821501 0.8181068 ]
 [0.89505224 0.7629443 ]
 [0.78514157 0.54649714]
 [0.72208387 0.3847633 ]
 [0.42639746 0.67388253]
 [0.73400021 0.4059016 ]]
<class 'numpy.ndarray'>


In [16]:
"""正規分布に従う乱数生成
"""
x=np.random.randn(10,2)
print(x)
print(type(x))

[[-0.78580039  0.61701498]
 [ 0.68870011 -0.93149232]
 [ 0.02663357 -0.52987713]
 [-0.92356563  0.76497403]
 [-2.13701082 -0.76063053]
 [ 1.14989536 -2.71139953]
 [-1.39379193 -2.34339382]
 [-0.02143499 -0.41315363]
 [ 1.64253148 -0.48220577]
 [-1.11189108  0.18426726]]
<class 'numpy.ndarray'>


## 要素の取得と置換
便利な要素の取得方法と置換方法を紹介します

In [17]:
"""通常
[行,列]
"""
x=np.array([[1,2,3], [4,5,6]])
print(x)
print(x[0,0])

[[1 2 3]
 [4 5 6]]
1


In [101]:
"""行
"""
x=np.array([[1,2,3], [4,5,6],[7,8,9]])
print(x)
print(x[0,:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]


In [104]:
"""列
"""
x=np.array([[1,2,3], [4,5,6],[7,8,9]])
print(x)
print(x[:,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 4 7]


In [18]:
"""条件
"""
x=np.array([[1,2,3], [4,5,6],[7,8,9]])
print(x)
print(x[x>5])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[6 7 8 9]


In [110]:
"""置換
基本的にリストなどと同じように、インデックス指定して値を代入すればよい
"""
x=np.array([[1,2,3], [4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [111]:
x[0,0]=1000
print(x)

[[1000    2    3]
 [   4    5    6]
 [   7    8    9]]


In [112]:
x[x<4]=0
print(x)

[[1000    0    0]
 [   4    5    6]
 [   7    8    9]]


## 結合と分割
複数の行列の結合方法と分割方法を紹介します

In [19]:
x1=np.array([[1,2,3], [4,5,6],[7,8,9]])
x2=np.arange(3)
print(x1)
print(x2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0 1 2]


In [20]:
"""縦方向結合
垂直：vertical
"""
x=np.vstack([x1,x2])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 1 2]]


In [23]:
"""横方向結合
水平：horizontal
"""
x=np.hstack([x1,x2])
print(x)

[[1 2 3 0]
 [4 5 6 1]
 [7 8 9 2]]


In [24]:
"""縦方向分割
"""
x=np.array([[1, 2, 3],[4, 5, 6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
print(np.vsplit(x,3))

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [27]:
"""横方向分割
"""
x=np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [28]:
print(np.hsplit(x,3))

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


## 行列計算
四則演算・内積・外積・統計量

In [123]:
"""四則演算
"""
x= np.array([1, 2, 3, 4, 5])

print(x+10)

[11 12 13 14 15]


In [124]:
print(x-10)
print(x*10)
print(x/10)
print(x**2)

[-9 -8 -7 -6 -5]
[10 20 30 40 50]
[0.1 0.2 0.3 0.4 0.5]
[ 1  4  9 16 25]


In [126]:
"""内積
"""
x1 = np.array([1, 2])
x2 = np.array([3, 4])
print(x1)
print(x2)

[1 2]
[3 4]


In [127]:
x=np.dot(x1 ,x2)
print(x)

11


In [128]:
"""行列同士の掛け算
"""
x1 = np.array([[1, 2],[3,4]])
x2 = np.array([10, 100])
print(x1)
print(x2)

[[1 2]
 [3 4]]
[ 10 100]


In [129]:
x=x1*x2
print(x)

[[ 10 200]
 [ 30 400]]


In [131]:
"""統計量の算出
"""
#正規分布で乱数生成
x1=np.random.randn(1000)
print(x1)

[ 9.32898018e-01  6.60755769e-01 -7.55078259e-01  1.15988545e+00
  1.88529979e-02  1.64463425e+00  9.47770359e-02 -1.31544243e+00
  4.43376316e-01 -1.33887001e+00 -4.82556363e-01  1.11104272e+00
 -1.71290651e+00 -2.21963232e+00 -4.11488427e-01 -6.59382657e-02
  1.36275202e+00 -1.96972184e+00 -1.29173395e+00 -2.24111977e+00
  9.34291654e-01 -1.78002170e+00  7.33403768e-01 -6.81302876e-01
  1.87649594e-01 -5.33701301e-01 -1.12181187e+00  6.10712185e-01
 -3.66180057e-01 -3.64296584e-01  9.38073760e-01  5.99515683e-01
  1.05121547e+00  4.30639712e-01 -6.89292461e-01  3.30748645e-01
  6.17540958e-01  1.01561572e+00 -8.08547811e-01 -8.02957948e-01
  9.64950858e-03 -5.42357416e-01 -6.70953855e-01 -4.37687244e-01
 -1.02855430e+00 -8.58362636e-01 -1.92720490e+00 -5.57770190e-01
 -1.14802058e+00  9.60294983e-01 -1.64747653e-01  3.50882919e-01
  7.01872833e-01  8.64675760e-01 -2.43786732e-01 -6.37206452e-01
 -2.10902636e-01  8.87726393e-02  1.20129382e-01  5.94321070e-01
 -1.29851858e+00 -1.11186

In [132]:
#最小値
print(np.min(x1))
#平均値
print(np.mean(x1))
#中央値
print(np.median(x1))
#最大値
print(np.max(x1))
#標準偏差
print(np.std(x1))
#分散
print(np.var(x1))

-3.2638631961998867
0.0020771608571514477
-0.014966486501903927
3.3231605733154406
1.0208972544187873
1.042231204079818


## numpy応用編
少し難しいが、役立つ小技集を紹介します

In [29]:
x = np.arange(25).reshape(5, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [73]:
#行列の構造
print(x.shape)

(5, 5)


In [74]:
#行列をリストに
print(x.tolist())

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19], [20, 21, 22, 23, 24]]


In [138]:
#行列の次元数
print(x.ndim)

2


In [139]:
#行列の要素数
print(x.size)

25


In [31]:
"""行列の各要素要素への関数の適用
"""
def func(a):
    return a**2

np_func = np.vectorize(func)
print(np_func(x))

[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


In [140]:
x =np.array([[2,32,1],[43,2000,-5],[-100,-2000,10]])
print(x)

[[    2    32     1]
 [   43  2000    -5]
 [ -100 -2000    10]]


In [78]:
#要素のソート（行ごと）
print(np.sort(x))

[[    1     2    32]
 [   -5    43  2000]
 [-2000  -100    10]]


In [79]:
#要素のソート（列ごと）
print(np.sort(x,axis=0))

[[ -100 -2000    -5]
 [    2    32     1]
 [   43  2000    10]]
